//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_repos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReposEntities : DbContext
    {
        public ReposEntities()
            : base("name=ReposEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<Responsable> Responsable { get; set; }
        public virtual DbSet<Repos> Repos { get; set; }
        public virtual DbSet<Demande_congé> Demande_congé { get; set; }
    }
}
