//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande_congé
    {
        public int Id_demende { get; set; }
        public int Id { get; set; }
        public int semaine { get; set; }
    }
}
